spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:

    url: jdbc:postgresql://82.180.160.174:5432/idosoprod
    username: idoso
    password: root
    driverClassName: org.postgresql.Driver

