spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:

    url: jdbc:postgresql://82.180.160.174:5432/idosoprod
    username: idoso
    password: root
    driverClassName: org.postgresql.Driver

