spring:
  application:
    name: Idoso-API

server:
  port: 9999

idoso:
  jwt:
    tokenExpirationTime: 60
    appSecret: rm!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\\}x3?JR3.2zr~v)gYF^8\\:8>:XfB:Ww75N
